[7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9, 6, 0, 5, 4, 9, 9, 2, 1, 9, 4, 8, 7, 3, 9, 7, 4, 4, 4, 9, 2, 5, 4, 7, 6, 7, 9, 0, 5, 8, 5, 6, 6, 5, 7, 8, 1, 0, 1, 6, 4, 6, 7, 3, 1, 7, 1, 8, 2, 0, 2, 9, 9, 5, 5, 1, 5, 6, 0, 3, 4, 4, 6, 5, 4, 6, 5, 4, 5, 1, 4, 4, 7, 2, 3, 2, 7, 1, 8, 1, 8, 1, 8, 5, 0, 8, 9, 2, 5, 0, 1, 1, 1, 0, 9, 0, 3, 1, 6, 4, 2, 3, 6, 1, 1, 1, 3, 9, 5, 2, 9, 4, 5, 9, 3, 9, 0, 3, 6, 5, 5, 7, 2, 2, 7, 1, 2, 8, 4, 1, 7, 3, 3, 8, 8, 7, 9, 2, 2, 4, 1, 5, 9, 8, 7, 2, 3, 0, 4, 4, 2, 4, 1, 9, 5, 7, 7, 2, 8, 2, 6, 8, 5, 7, 7, 9, 1, 8, 1, 8, 0, 3, 0, 1, 9, 9, 4, 1, 8, 2, 1, 2, 9, 7, 5, 9, 2, 6, 4, 1, 5, 8, 2, 9, 2, 0, 4, 0, 0, 2, 8, 4, 7, 1, 2, 4, 0, 2, 7, 4, 3, 3, 0, 0, 3, 1, 9, 6, 5, 2, 5, 9, 2, 9, 3, 0, 4, 2, 0, 7, 1, 1, 2, 1, 

In [1]:
import tensorflow as tf

factor = tf.Variable(2, dtype = tf.float32)
array = tf.random_normal([3], stddev = 0.5)
state = tf.Variable(array, dtype = tf.float32)
state = tf.multiply(factor, state)
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    for i in range(3):
        print(session.run(state))

[ 0.26235017 -1.08450758 -0.51568556]
[ 0.26235017 -1.08450758 -0.51568556]
[ 0.26235017 -1.08450758 -0.51568556]


In [12]:
x = tf.placeholder(tf.float32, None)
label = tf.placeholder(tf.float32, None)
weight = tf.Variable(0.5)
output = x * weight
loss = 0.5 * tf.square(label - output)
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.5)
optimization_step = optimizer.minimize(loss)
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    for step in range(15):
        _loss, _weight, _ = session.run([loss, weight, optimization_step],feed_dict = {x: 1, label: 5})
        print(_loss, _weight)

10.125 2.75
2.53125 3.875
0.632813 4.4375
0.158203 4.71875
0.0395508 4.85938
0.0098877 4.92969
0.00247192 4.96484
0.000617981 4.98242
0.000154495 4.99121
3.86238e-05 4.99561
9.65595e-06 4.9978
2.41399e-06 4.9989
6.03497e-07 4.99945
1.50874e-07 4.99973
3.77186e-08 4.99986
